-- Additional Enhancement: Favorites + Notes
-- Run this against your cse340 database.

CREATE TABLE IF NOT EXISTS public.account_favorite (
  favorite_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INT NOT NULL,
  inv_id INT NOT NULL,
  note VARCHAR(200),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_fav_account FOREIGN KEY (account_id)
    REFERENCES public.account (account_id) ON DELETE CASCADE,
  CONSTRAINT fk_fav_inventory FOREIGN KEY (inv_id)
    REFERENCES public.inventory (inv_id) ON DELETE CASCADE,
  CONSTRAINT uq_fav_account_inv UNIQUE (account_id, inv_id)
);

