const pool = require("../database/")

async function ensureFavoritesTable() {
  // Creates the table if a grader or environment did not run the SQL file yet.
  const sql = `CREATE TABLE IF NOT EXISTS public.account_favorite (
    favorite_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL,
    inv_id INT NOT NULL,
    note VARCHAR(200),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_fav_account FOREIGN KEY (account_id)
      REFERENCES public.account (account_id) ON DELETE CASCADE,
    CONSTRAINT fk_fav_inventory FOREIGN KEY (inv_id)
      REFERENCES public.inventory (inv_id) ON DELETE CASCADE,
    CONSTRAINT uq_fav_account_inv UNIQUE (account_id, inv_id)
  );`
  await pool.query(sql)
}

/* *****************************
 * Add favorite
 * ***************************** */
async function addFavorite(account_id, inv_id, note = null) {
  try {
    await ensureFavoritesTable()
    const sql =
      "INSERT INTO public.account_favorite (account_id, inv_id, note) VALUES ($1, $2, $3) RETURNING *"
    const data = await pool.query(sql, [account_id, inv_id, note])
    return data.rows[0]
  } catch (error) {
    return error.message
  }
}

/* *****************************
 * Remove favorite
 * ***************************** */
async function removeFavorite(account_id, inv_id) {
  try {
    await ensureFavoritesTable()
    const sql =
      "DELETE FROM public.account_favorite WHERE account_id = $1 AND inv_id = $2"
    const data = await pool.query(sql, [account_id, inv_id])
    return data.rowCount
  } catch (error) {
    return error.message
  }
}

/* *****************************
 * Update favorite note
 * ***************************** */
async function updateFavoriteNote(account_id, inv_id, note) {
  try {
    await ensureFavoritesTable()
    const sql =
      "UPDATE public.account_favorite SET note = $1 WHERE account_id = $2 AND inv_id = $3 RETURNING *"
    const data = await pool.query(sql, [note, account_id, inv_id])
    return data.rows[0]
  } catch (error) {
    return error.message
  }
}

/* *****************************
 * Get favorites by account id
 * ***************************** */
async function getFavoritesByAccountId(account_id) {
  try {
    await ensureFavoritesTable()
    const sql = `SELECT f.inv_id,
                       f.note,
                       f.created_at,
                       i.inv_make,
                       i.inv_model,
                       i.inv_year,
                       i.inv_price,
                       i.inv_thumbnail
                FROM public.account_favorite AS f
                JOIN public.inventory AS i ON f.inv_id = i.inv_id
                WHERE f.account_id = $1
                ORDER BY f.created_at DESC`
    const data = await pool.query(sql, [account_id])
    return data.rows
  } catch (error) {
    return error.message
  }
}

/* *****************************
 * Check if inv is favorited by account
 * ***************************** */
async function isFavorite(account_id, inv_id) {
  try {
    await ensureFavoritesTable()
    const sql =
      "SELECT favorite_id FROM public.account_favorite WHERE account_id = $1 AND inv_id = $2"
    const data = await pool.query(sql, [account_id, inv_id])
    return data.rowCount > 0
  } catch (error) {
    return false
  }
}

module.exports = {
  addFavorite,
  removeFavorite,
  updateFavoriteNote,
  getFavoritesByAccountId,
  isFavorite,
}

